(() => {
 'use strict';
 let target,timer,revision=0,busy=false,config,undo,bubble,panel,root,marks,checkedValue,checkedMatches=[],panelAnchor,panelRevision=0;
 const excluded=new Set(['password','email','tel','number','hidden','button','submit','checkbox','radio','file','date','color']);
 const sensitive=/api.?key|secret|token|authorization|password|current-password|new-password|one-time-code|cc-|credit.?card|cvc|cvv|card.?number/i;
 function editable(node){const e=node?.closest?.('textarea,input,[contenteditable="true"],[contenteditable="plaintext-only"]');if(!e||e.disabled||e.readOnly||e.dataset.qubiteWriting==='off')return null;
  if(e.tagName==='INPUT'&&(excluded.has(e.type)||!['text','search','url'].includes(e.type)))return null;
  if(sensitive.test([e.autocomplete,e.name,e.id].join(' ')))return null;return e;}
 function text(e){return e?.isContentEditable?e.innerText:e?.value||'';}
 function selection(e){const value=text(e);if(!e.isContentEditable&&typeof e.selectionStart==='number'&&e.selectionEnd>e.selectionStart)return {text:value.slice(e.selectionStart,e.selectionEnd),start:e.selectionStart,end:e.selectionEnd,whole:value};return {text:value,start:0,end:value.length,whole:value};}
 function dom(tag,value,parent=panel){const e=document.createElement(tag);if(value)e.textContent=value;parent.append(e);return e;}
 function button(label,fn,parent=panel){const b=dom('button',label,parent);b.type='button';b.onclick=e=>{if(e.isTrusted)fn();};return b;}
 function indicator(state,label){if(!bubble)return;bubble.dataset.state=state;bubble.firstChild.textContent=label;bubble.setAttribute('aria-label',state==='errors'?'Qubite: замечаний '+label:state==='clean'?'Qubite: ошибок не найдено':'Qubite: проверка текста');}
 function close(){panelRevision++;if(panel)panel.hidden=true;panelAnchor=null;}
 function clearMarks(){marks?.clear();checkedValue=undefined;checkedMatches=[];}
 function setup(){if(root)return;const host=document.createElement('div');host.style.cssText='all:initial;position:fixed;z-index:2147483646;top:0;left:0';document.documentElement.append(host);root=host.attachShadow({mode:'closed'});
  const style=document.createElement('style');style.textContent=`:host{all:initial}*{box-sizing:border-box}.bubble{position:fixed;width:24px;height:24px;border:1px solid transparent;border-radius:8px;background:linear-gradient(#192332,#192332) padding-box,linear-gradient(90deg,#f43f5e,#f59e0b) border-box;font:700 12px/1 system-ui;padding:0;cursor:pointer;box-shadow:0 2px 8px #0003;display:grid;place-items:center}.bubble[data-state=clean]{background:linear-gradient(#123328,#123328) padding-box,linear-gradient(90deg,#f43f5e,#f59e0b) border-box;box-shadow:0 0 0 2px #34d39925}.bubble[data-state=errors]{background:linear-gradient(#421c28,#421c28) padding-box,linear-gradient(90deg,#f43f5e,#f59e0b) border-box;box-shadow:0 0 0 2px #fb718525}.bubble span{background:linear-gradient(90deg,#f43f5e,#f59e0b);background-clip:text;-webkit-background-clip:text;color:transparent}.bubble:focus-visible,.panel button:focus-visible{outline:2px solid #fbbf24;outline-offset:3px}.panel{position:fixed;width:min(380px,calc(100vw - 24px));max-height:70vh;overflow:auto;background:#0b1220;color:#e2e8f0;border:1px solid transparent;background:linear-gradient(#0b1220,#0b1220) padding-box,linear-gradient(90deg,#f43f5e,#f59e0b) border-box;border-radius:14px;padding:16px;box-shadow:0 12px 40px #0008;font:14px/1.5 system-ui}.panel button,.panel select,.panel input{background:#263245;color:#e2e8f0;border:1px solid #52617a;border-radius:7px;padding:8px;margin:4px 4px 4px 0;font:inherit;cursor:pointer}.panel p{margin:8px 0;overflow-wrap:anywhere}.panel pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:220px;overflow:auto;font:inherit}.panel input{max-width:100%}[hidden]{display:none!important}`;root.append(style);
  bubble=document.createElement('button');bubble.className='bubble';bubble.append(document.createElement('span'));indicator('pending','✓');bubble.title='Qubite: проверить текст';bubble.onclick=e=>{if(e.isTrusted){panel.hidden?menu():close();}};root.append(bubble);panel=document.createElement('div');panel.className='panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Редактор Qubite');root.append(panel);marks=new QubiteWritingMarks((m,rect,event)=>{if(event.isTrusted)issue(m,rect);});root.addEventListener('keydown',e=>{if(e.key==='Escape'){close();bubble.focus();}});
 }
 function position(){if(!target?.isConnected){if(bubble)bubble.hidden=true;close();clearMarks();return;}const r=target.getBoundingClientRect();bubble.hidden=r.bottom<0||r.top>innerHeight||r.right<0||r.left>innerWidth;
  bubble.style.left=Math.max(4,Math.min(innerWidth-28,r.right-32))+'px';bubble.style.top=Math.max(4,Math.min(innerHeight-28,r.bottom-30))+'px';
  const anchor=panelAnchor||{left:r.right-380,bottom:r.bottom};panel.style.left=Math.max(12,Math.min(innerWidth-panel.offsetWidth-12,anchor.left))+'px';panel.style.top=Math.max(12,Math.min(innerHeight-panel.offsetHeight-12,anchor.bottom+8))+'px';
 }
 function issue(m,rect){if(!target||text(target)!==checkedValue){clearMarks();close();return;}const e=target,value=checkedValue;panelAnchor=rect;panel.hidden=false;panel.replaceChildren();dom('strong',value.slice(m.offset,m.offset+m.length)||'Пропущенный знак');dom('p',m.message);
  for(const r of m.replacements.slice(0,5))button(r.value||'Удалить',()=>{if(apply(e,{whole:value,start:m.offset,end:m.offset+m.length},r.value)){close();check(false);}});
  if(!m.replacements.length)dom('p','Готового варианта нет — исправь вручную.');button('Все замечания',()=>showMatches(e,value,checkedMatches));button('Закрыть',close);position();
 }
 function showMatches(e,value,matches){panelAnchor=null;panel.hidden=false;panel.replaceChildren();dom('strong','Локальная проверка');dom('p',matches.length?'Замечаний: '+matches.length:'Локальные правила не нашли ошибок. Сложные случаи можно проверить ИИ.');
  for(const m of matches){dom('p',m.message+' · «'+value.slice(m.offset,m.offset+m.length)+'»');for(const r of m.replacements.slice(0,3))button(r.value||'Удалить',()=>{if(apply(e,{whole:value,start:m.offset,end:m.offset+m.length},r.value)){close();check(true);}});}
  button('Назад',menu);button('Закрыть',close);position();
 }
 function note(message){panelAnchor=null;panel.hidden=false;panel.replaceChildren();dom('p',message);button('Закрыть',close);position();}
 function menu(){if(!target)return;panelAnchor=null;panel.replaceChildren();panel.hidden=false;dom('strong','Qubite Writing');dom('p','Выдели фрагмент для ИИ или проверь всё поле.');
  button('Локальная проверка',()=>check(true));if(checkedValue===text(target)&&checkedMatches.length)button('Замечания: '+checkedMatches.length,()=>showMatches(target,checkedValue,checkedMatches));button('ИИ-проверка',()=>rewrite('check'));button('Улучшить в моём стиле',()=>rewrite('improve'));button('Улучшить промпт',()=>rewrite('prompt'));
  const styles=dom('select');styles.setAttribute('aria-label','Стиль');for(const v of ['простой и понятный','дружелюбный разговорный','деловой','академический','краткий и прямой','свой стиль']){const o=dom('option',v,styles);o.value=v;}
  const custom=dom('input');custom.placeholder='Опиши свой стиль';custom.maxLength=200;custom.hidden=true;styles.onchange=()=>{custom.hidden=styles.value!=='свой стиль';};button('Сменить стиль',()=>rewrite('style',styles.value==='свой стиль'?custom.value:styles.value));
  if(undo&&text(target)===undo.after)button('Отменить замену',()=>{setText(target,undo.before);undo=null;note('Замена отменена.');});
  button('Не проверять этот сайт',async()=>{config.blocked.push(location.hostname);await browser.storage.local.set({blocked:config.blocked});bubble.hidden=true;panel.hidden=true;target=null;clearMarks();clearTimeout(timer);});button('Закрыть',close);position();
 }
 function setText(e,value){clearMarks();indicator('pending','…');e.focus();if(e.isContentEditable){const range=document.createRange();range.selectNodeContents(e);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);if(!document.execCommand('insertText',false,value))throw new Error('Это поле не поддерживает замену. Скопируй результат вручную.');}
  else{const proto=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new Event('input',{bubbles:true}));}
 }
 function apply(e,source,result){if(!e.isConnected||text(e)!==source.whole){note('Поле изменилось. Результат не вставлен:');dom('pre',result);return false;}const value=source.whole.slice(0,source.start)+result+source.whole.slice(source.end);if(!e.isContentEditable&&e.maxLength>0&&value.length>e.maxLength){note('Результат превышает лимит поля. Скопируй его вручную:');dom('pre',result);return false;}setText(e,value);undo={before:source.whole,after:value};return true;}
 async function check(show){clearTimeout(timer);if(busy||!target)return;const e=target,value=text(e),n=revision,view=panelRevision;if(!value.trim()||value.length>8000){clearMarks();indicator('pending','✓');return;}busy=true;indicator('pending','…');try{
  const data=await browser.runtime.sendMessage({kind:'request',action:'check',body:{text:value,language:config?.language||'ru'}});if(e!==target||n!==revision||text(e)!==value)return;
  checkedValue=value;checkedMatches=data.matches;marks.set(e,value,data.matches);indicator(data.matches.length?'errors':'clean',data.matches.length?String(Math.min(99,data.matches.length)):'✓');if(show&&view===panelRevision)showMatches(e,value,data.matches);
 }catch(error){if(e===target&&n===revision){clearMarks();indicator('pending','!');if(show&&view===panelRevision)note(error.message);}}finally{busy=false;if(target&&(n!==revision||e!==target)&&config?.automatic){clearTimeout(timer);timer=setTimeout(()=>check(false),500);}}}
 async function rewrite(mode,style){if(busy||!target)return;clearTimeout(timer);const e=target,source=selection(e);if(!source.text.trim())return;busy=true;note('ИИ редактирует…');try{
  const data=await browser.runtime.sendMessage({kind:'request',action:'rewrite',body:{text:source.text,mode,style}});
  if(apply(e,source,data.text)){note('Текст заменён · '+data.model+'.');button('Отменить',()=>{if(text(e)!==undo.after){note('После замены текст изменился. Автоматическая отмена недоступна.');return;}setText(e,undo.before);undo=null;note('Замена отменена.');});}
  for(const s of [...data.notes,...data.questions])dom('p',s);button('Меню',menu);position();
 }catch(error){note(error.message);}finally{busy=false;if(config?.automatic){clearTimeout(timer);timer=setTimeout(()=>check(false),500);}}}
 function blocked(){return config?.blocked.some(d=>location.hostname===d||location.hostname.endsWith('.'+d));}
 document.addEventListener('pointerdown',e=>{if(!root||e.composedPath().includes(root.host))return;close();},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape')close();},true);
 document.addEventListener('focusin',async e=>{if(!config)config=await browser.runtime.sendMessage({kind:'config'});if(!config.configured||blocked())return;const next=editable(document.activeElement);if(!next){if(e.target!==root?.host){target=null;revision++;clearTimeout(timer);clearMarks();if(bubble)bubble.hidden=true;close();}return;}if(next!==target){target=next;revision++;undo=null;clearMarks();setup();indicator('pending','✓');close();clearTimeout(timer);if(config.automatic&&text(target).trim())timer=setTimeout(()=>check(false),500);}setup();position();},true);
 document.addEventListener('input',e=>{if(e.target!==target&&!target?.contains(e.target))return;revision++;clearMarks();close();indicator('pending','…');clearTimeout(timer);if(config?.automatic&&!blocked())timer=setTimeout(()=>check(false),2000);},true);
 addEventListener('scroll',position,true);addEventListener('resize',position);
 browser.runtime.onMessage.addListener(m=>{if(m.contextAction){target=editable(document.activeElement)||target;if(!target)return;setup();position();if(m.contextAction==='menu')menu();else rewrite(m.contextAction);}});
})();
