#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

ask() {
  local name="$1" prompt="$2" default="${3:-}" secret="${4:-}"
  [[ -n "${!name:-}" ]] && return
  local suffix=""
  [[ -n "$default" ]] && suffix=" [$default]"
  if [[ "$secret" == "secret" ]]; then
    read -r -s -p "$prompt$suffix: " "$name"
    echo
  else
    read -r -p "$prompt$suffix: " "$name"
  fi
  [[ -z "${!name}" && -n "$default" ]] && printf -v "$name" "%s" "$default"
}

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
ask PROXY_DOMAIN "Proxy domain of this node" "proxy.qubiteapp.online"
ask PROXY_EXTRA_DOMAINS "Extra proxy domains, comma separated" ""
ask MAIN_SITE_DOMAIN "Main website domain for browser redirect" "qubiteapp.ru"
ask MASTER_API_BASE_URL "Master Qubite API base URL" "https://${MAIN_SITE_DOMAIN}"
ask PROXY_NODE_TOKEN "Node token from owner panel" "" secret

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y golang-go git nodejs curl libcap2-bin ufw

if [[ -f /etc/default/ufw ]]; then
  sed -i 's/^IPV6=.*/IPV6=yes/' /etc/default/ufw
fi

if [[ ! -x /usr/local/bin/xcaddy ]]; then
  GOBIN=/usr/local/bin go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
fi

/usr/local/bin/xcaddy build \
  --output /usr/local/bin/caddy-naive \
  --with github.com/caddyserver/forwardproxy@caddy2
setcap cap_net_bind_service=+ep /usr/local/bin/caddy-naive || true

mkdir -p /etc/caddy /var/lib/caddy /var/log/caddy
cat >/etc/caddy/forwardproxy-credentials.caddy <<'EOF_CREDS'
basic_auth bootstrap bootstrap-change-me
EOF_CREDS
cat >/etc/caddy/qubite-sni-routes.caddy <<'EOF_SNI'
# Generated by Qubite proxy sync. Do not edit manually.
EOF_SNI
chmod 600 /etc/caddy/forwardproxy-credentials.caddy
chmod 600 /etc/caddy/qubite-sni-routes.caddy

PROXY_SITE_NAMES="$PROXY_DOMAIN"
IFS=',' read -ra PROXY_EXTRA <<<"$PROXY_EXTRA_DOMAINS"
for domain in "${PROXY_EXTRA[@]}"; do
  domain="$(echo "$domain" | xargs)"
  [[ -n "$domain" ]] && PROXY_SITE_NAMES="${PROXY_SITE_NAMES}, https://${domain}"
done

cat >/etc/caddy/Caddyfile <<EOF_CADDY
{
    order forward_proxy before reverse_proxy
    admin 127.0.0.1:2019
}

https://${PROXY_SITE_NAMES}, :443 {
    route {
        forward_proxy {
            import /etc/caddy/forwardproxy-credentials.caddy
            hide_ip
            hide_via
            probe_resistance
        }

        redir https://${MAIN_SITE_DOMAIN}{uri} 302
    }
}

import /etc/caddy/qubite-sni-routes.caddy
EOF_CADDY

SYNC_URL="${MASTER_API_BASE_URL%/}/api/proxy/sync/credentials"
HEARTBEAT_URL="${MASTER_API_BASE_URL%/}/api/proxy/node/heartbeat"

cat >/etc/systemd/system/caddy-naive.service <<'EOF_SERVICE'
[Unit]
Description=Caddy NaiveProxy frontend
After=network-online.target
Wants=network-online.target

[Service]
User=root
Group=root
ExecStart=/usr/local/bin/caddy-naive run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/local/bin/caddy-naive reload --config /etc/caddy/Caddyfile --force
Restart=on-failure
RestartSec=5s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF_SERVICE

cat >/etc/systemd/system/qubite-proxy-sync.service <<EOF_SERVICE
[Unit]
Description=Sync Qubite proxy credentials into Caddy
After=network-online.target

[Service]
Type=oneshot
Environment=PROXY_NODE_TOKEN=${PROXY_NODE_TOKEN}
Environment=PROXY_SYNC_TOKEN=${PROXY_NODE_TOKEN}
Environment=QUBITE_PROXY_SYNC_URL=${SYNC_URL}
Environment=CADDY_FORWARDPROXY_CREDENTIALS=/etc/caddy/forwardproxy-credentials.caddy
ExecStart=/usr/bin/node ${REPO_DIR}/deploy/proxy/sync-caddy-credentials.mjs
ExecStartPost=/usr/bin/systemctl reload caddy-naive.service
EOF_SERVICE

cat >/etc/systemd/system/qubite-proxy-sync.timer <<'EOF_TIMER'
[Unit]
Description=Refresh Qubite proxy credentials for Caddy

[Timer]
OnBootSec=30s
OnUnitActiveSec=30s
AccuracySec=5s
Unit=qubite-proxy-sync.service

[Install]
WantedBy=timers.target
EOF_TIMER

cat >/etc/systemd/system/qubite-proxy-heartbeat.service <<EOF_SERVICE
[Unit]
Description=Send Qubite proxy node heartbeat
After=network-online.target

[Service]
Type=oneshot
Environment=PROXY_NODE_TOKEN=${PROXY_NODE_TOKEN}
Environment=QUBITE_PROXY_HEARTBEAT_URL=${HEARTBEAT_URL}
ExecStart=/usr/bin/node ${REPO_DIR}/deploy/proxy/proxy-node-heartbeat.mjs
EOF_SERVICE

cat >/etc/systemd/system/qubite-proxy-heartbeat.timer <<'EOF_TIMER'
[Unit]
Description=Send Qubite proxy node heartbeat periodically

[Timer]
OnBootSec=45s
OnUnitActiveSec=60s
AccuracySec=10s
Unit=qubite-proxy-heartbeat.service

[Install]
WantedBy=timers.target
EOF_TIMER

ufw allow 22/tcp >/dev/null || true
ufw allow 80/tcp >/dev/null || true
ufw allow 443/tcp >/dev/null || true

/usr/local/bin/caddy-naive validate --config /etc/caddy/Caddyfile
systemctl daemon-reload
systemctl enable caddy-naive.service qubite-proxy-sync.timer qubite-proxy-heartbeat.timer >/dev/null
systemctl restart caddy-naive.service
systemctl restart qubite-proxy-sync.service || true
systemctl restart qubite-proxy-heartbeat.service || true
systemctl start qubite-proxy-sync.timer qubite-proxy-heartbeat.timer

echo "Proxy node installed."
echo "Proxy domain: https://${PROXY_DOMAIN}"
echo "Browser fallback: https://${MAIN_SITE_DOMAIN}"
echo "Master API: ${MASTER_API_BASE_URL}"
