const test=require('node:test'),assert=require('node:assert/strict'),express=require('express'),fs=require('fs'),os=require('os'),path=require('path');
process.env.APP_BASE_URL='https://qubiteapp.online';process.env.SERVICES_SIYUAN_BASE_URL='https://siyuan.qubiteapp.online';
const m=require('../src/siyuan');let server,base;
test.before(async()=>{const app=express();app.use((q,s,n)=>{if(q.headers['x-test-role'])q.auth={user:{role:q.headers['x-test-role'],actual_role:q.headers['x-test-actual']}};n();});m.register(app,{internalKey:(q,s,n)=>q.headers['x-test-key']==='internal'?n():s.status(403).end()});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));base='http://127.0.0.1:'+server.address().port;});
test.after(()=>new Promise(r=>server.close(r)));
const h={'x-test-key':'internal'},get=(p,headers={})=>fetch(base+p,{headers:{...h,...headers},redirect:'manual'});
test('exact personal origin and real owner only',()=>{for(const v of ['//evil','/\\evil','https://siyuan.qubiteapp.online/','/test\n'])assert.equal(m.target(v),null);assert.equal(m.target('/?q=one'),'https://siyuan.qubiteapp.online/?q=one');assert.equal(m.owner({role:'owner',actual_role:'admin'}),false);});
test('anonymous users return to Qubite while API and other accounts are denied',async()=>{let r=await get('/internal/services/siyuan-access',{'x-forwarded-uri':'/stage/build/desktop/'});assert.equal(r.status,302);assert.equal(new URL(r.headers.get('location')).searchParams.get('return_to'),'https://siyuan.qubiteapp.online/stage/build/desktop/');assert.equal((await get('/internal/services/siyuan-access',{'x-forwarded-uri':'/api/query/sql'})).status,401);for(const role of ['user','admin','moderator'])assert.equal((await get('/internal/services/siyuan-access',{'x-test-role':role})).status,403);});
test('owner gets native cookie session; native cookie cannot replace Qubite identity',async()=>{const headers={'x-test-role':'owner',cookie:'siyuan=signed'};assert.equal((await get('/internal/services/siyuan-access',headers)).status,200);assert.equal((await get('/internal/services/siyuan-access',{cookie:'siyuan=signed'})).status,302);assert.equal((await get('/internal/services/siyuan-access',{'x-test-role':'owner'})).status,302);});
test('cross-origin writes and websockets require exact origin; phishing returns denied',async()=>{for(const headers of [{'x-forwarded-method':'POST'},{origin:'https://evil.example'},{'x-forwarded-uri':'/ws'}])assert.equal((await get('/internal/services/siyuan-access',{'x-test-role':'owner',cookie:'siyuan=x',...headers})).status,403);assert.equal((await get('/internal/services/siyuan-access',{'x-test-role':'owner',cookie:'siyuan=x',origin:m.url(),'x-forwarded-method':'POST'})).status,200);assert.equal((await get('/internal/services/siyuan-session?return_to=//evil',{'x-test-role':'owner'})).status,400);assert.equal((await get('/internal/services/siyuan-session?return_to=/_qubite/session',{'x-test-role':'owner'})).status,400);});
test('session cookies are scoped, HttpOnly and Secure, without leaking the native secret',async()=>{
 const f=path.join(os.tmpdir(),'siyuan-test-'+process.pid);fs.writeFileSync(f,JSON.stringify({auth_code:'test-secret'}));process.env.SIYUAN_PRIVATE_FILE=f;const original=global.fetch;global.fetch=async(url,opts)=>{if(url.startsWith('http://127.0.0.1:6806')){assert.equal(JSON.parse(opts.body).authCode,'test-secret');return {ok:true,json:async()=>({code:0}),headers:{getSetCookie:()=>['siyuan=signed; Path=/; HttpOnly; SameSite=Lax']}};}return original(url,opts);};
 try{const r=await get('/internal/services/siyuan-session?return_to=/stage/build/desktop/',{'x-test-role':'owner'});assert.equal(r.status,302);assert.match(r.headers.get('set-cookie'),/HttpOnly.*Secure/);assert.equal(r.headers.get('location'),m.url()+'/stage/build/desktop/');assert.ok(!(await r.text()).includes('test-secret'));}finally{global.fetch=original;fs.unlinkSync(f);}
});
